events {}

http {

    resolver 127.0.0.11 valid=30s;

    upstream frontend_upstream {
        server frontend:80;
    }

    upstream backend_upstream {
        server backend:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_upstream;
        }

        location /api {
            proxy_pass http://backend_upstream;
        }
    }
}
